site_name: FarmShare
site_url: https://docs.farmshare.stanford.edu/
site_description: >
  User documenation for FarmShare, Stanford's cluster for teaching,
  coursework, and unsponsored research.
site_author: Stanford | Research Computing

copyright: >-
  &copy <a href='mailto:srcc-support@stanford.edu'>
  <span style="color: #8C1515;"><strong>Stanford</strong></span> | Research Computing</a><br/>

docs_dir: src
site_dir: site

theme:
  name: material
  custom_dir: overrides

  language: en

  palette:
  # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: stanford
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      # https://github.com/squidfunk/mkdocs-material/issues/5537
      primary: custom
      accent:  custom
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

  font:
    text: Roboto
    code: Roboto Mono

extra_css:
  - assets/stylesheets/extra.css

extra_javascript:
  - assets/scripts/custom.js

extra:
  social:
    - icon: fontawesome/solid/wheelchair
      link: https://www.stanford.edu/site/accessibility
      name: Digital Accessibility at Stanford
    - icon: fontawesome/solid/earth-americas
      link: https://srcc.stanford.edu
      name: SRC website
    - icon: fontawesome/brands/github
      link: https://github.com/stanford-rc
      name: SRC on GitHub
    - icon: fontawesome/brands/bluesky
      link: https://bsky.app/profile/stanford-rc.bsky.social
      name: SRC on Bluesky
    - icon: fontawesome/brands/slack
      link: https://srcc.slack.com/
      name: SRC Users Slack workspace

markdown_extensions:
    - admonition
    - fenced_code
    - nl2br
    - smarty
    - tables
    - toc:
        permalink: True

nav:
  - "Introduction": index.md
  - "Getting Connected": docs/connecting.md
  - "Running Jobs": docs/slurm.md
  - "Using Software": docs/software.md
  - "Shared Storage": docs/storage.md
  - "Transferring Data": docs/transfer.md
  - "Adding Capacity": docs/capacity.md
  - "Getting Help": docs/help.md
  - "Policy": docs/policy.md
